$(document).ready(function(){
	$('#f0').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t0').addClass('show').removeClass('hide');
	});
	$('#f1').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t1').addClass('show').removeClass('hide');
	});
	$('#f2').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t2').addClass('show').removeClass('hide');
	});
	$('#f3').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t3').addClass('show').removeClass('hide');
	});
	$('#f4').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t4').addClass('show').removeClass('hide');
	});
	$('#f5').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t5').addClass('show').removeClass('hide');
	});
	$('#f6').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t6').addClass('show').removeClass('hide');
	});
	$('#f7').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t7').addClass('show').removeClass('hide');
	});
	$('#f8').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t8').addClass('show').removeClass('hide');
	});
	$('#f9').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t9').addClass('show').removeClass('hide');
	});
	$('#f10').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t10').addClass('show').removeClass('hide');
	});
	$('#f11').on('click',function(){
		$('.formulario').addClass('hide').removeClass('show');
		$('#t11').addClass('show').removeClass('hide');
	});
});